# This is a basic workflow to help you get started with Actions

name: yaml

# Controls when the workflow will run
on:
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
