# This is a basic workflow to help you get started with Actions

name: YUVI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  issues:
    types: [created]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
job1:
auto-assign:
        runs-on: ubuntu-latest
        steps:
            - name: 'Auto-assign issue'
              uses: pozil/auto-assign-issue@v1
              with:
                  assignees: darshilsoni10,jayamlakhaire1,raujeshpujari24,ajay-chavan-pd
                  numOfAssignee: 1
                  allowSelfAssign: false

job2:
runs-on: ubuntu-latest
  steps:
    - name: View issue information
    run: |
    echo "Issue title: ${{ github.event.issue.title }}"
    echo "Issue body: ${{ github.event.issue.body }}"
 name: Issue assignment  
